---
- name: Install Prometheus
  become: yes
  apt:
    name: prometheus
    state: present
    update_cache: yes

- name: Ensure Prometheus is running
  become: yes
  systemd:
    name: prometheus
    enabled: yes
    state: started

- name: Add Node Exporter targets to Prometheus config
  become: yes
  copy:
    dest: /etc/prometheus/prometheus.yml
    content: |
      global:
        scrape_interval: 15s

      scrape_configs:
        - job_name: 'node_exporter'
          static_configs:
            - targets: ['app_server_private_ip:9100']
                



  
